# jekyll configurations
title: Victor's Blog
author: Victor Preuss
email: vhpreuss@yahoo.com
description: >- # this means to ignore newlines until "baseurl:"
    A blog about embedded systems, RF electronics, Linux and open-source stuff.
url: "https://vpreuss.xyz" # the base hostname & protocol for your site

minima:
    date_format: "%b %-d, %Y"

    social_links:
        twitter: eletricitor
        github: victorpreuss
        linkedin: victor-preuss-a76a56100

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
